// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utneimavxjfgiqwbuufs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0bmVpbWF2eGpmZ2lxd2J1dWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTQyNzcsImV4cCI6MjA4ODU3MDI3N30.KXtL8xkyNOjRMKQsl20zRLXYr2xiMb8f2G9GQMe8Z1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});